### ISSUE TITLE
Add a non root account

### ISSUE THREAD

**Issue by 8BitJosh** [srobo/robot-image#34]
Add a not root account for student to log into the pi with.
Give the account the correct permissions (sudo, etc..)

**Comment by sedders123** [comment]
Can we just let competitors use root? Worst case they reflash the SD card. (I may be missing something massively obvious not been super involved with kit stuff apologies)

**Comment by trickeydan** [comment]
> Can we just let competitors use root? Worst case they reflash the SD card. (I may be missing something massively obvious not been super involved with kit stuff apologies)

We could, but we really shouldn't be encouraging bad practices. I believe the plan here is to add sudo perms to the account too.
