### ISSUE TITLE
Python thinks pyapriltags is version 0.0.0

### ISSUE THREAD

**Issue by trickeydan** [srobo/robot-image#64]
We must be doing something wrong with the metadata when unpacking the wheel

**Comment by WillB97** [comment]
This is a bug in april_vision's source tarball that will be corrected in the next release.

**Comment by trickeydan** [comment]
> april_vision's source tarball

Does this need to be fixed in pyapriltags also?

**Comment by WillB97** [comment]
pyapriltags looks to have the correct version in the latest image
